### ISSUE TITLE
Regarding the Type Embedding

### ISSUE THREAD

**Issue by tahmedge** [yasumasaonoe/InterpretableEntityRepresentation#1]
Hi, thanks for sharing the code. 

I would like to know, how is the Type Embedding constructed, is it randomly initialized?

**Comment by yasumasaonoe** [comment]
Hi,

Thanks for checking our work! The type embedding matrix is defined [here](https://github.com/yasumasaonoe/InterpretableEntityRepresentation/blob/805634dddbf25d48932c651ca50a262024d508de/models.py#L23) as a weight matrix of a linear layer. Yes, it's randomly initialized.

**Comment by tahmedge** [comment]
Thanks a lot for the clarification.
